name: 'run-circleci-artifacts-redirector'
description: 'Create a direct artifact link upon CircleCI completion'
branding:
  icon: check
  color: black
author: 'Eric Larson'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  artifact-path:
    description: 'Path to the CircleCI artifact'
    required: true
  circleci-jobs:
    description: 'Comma-separated list of CircleCI jobs to monitor (default is "build_docs,build,doc")'
    required: false
  api-token:
    description: 'CircleCI API token secret, only needed if the repository is private'
    required: false
  job-title:
    description: 'The name of the job, as it will render on the PR GUI (default is "<name of CI job> artifact)"'
    required: false
  domain:
    description: 'The domain on which CircleCI artifacts are hosted. Defaults to output.circle-artifacts.com.'
    required: false
    default: 'output.circle-artifacts.com'
outputs:
  url:
    description: 'The full redirect URL'
on: status
runs:
  using: 'node20'
  main: 'dist/index.js'
