version: 2.1
orbs:
  node: circleci/node@7.1.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '20.18.1'
      - run: node --version && npm install
      - run: |
          mkdir ~/my_test_artifacts
          echo "This should point to root_artifact.md for commit ${CIRCLE_SHA1}" > ~/my_test_artifacts/root_artifact.md
      - run: npm test
      - store_artifacts:
          path: ~/my_test_artifacts
          destination: test_artifacts
